### ISSUE TITLE
No lua-5.2 support in proctrack lua plugin

### ISSUE THREAD

**Issue by rfehren** [SchedMD/slurm#108]
Please pull https://github.com/Q-Leap-Networks/qlustar-slurm/pull/1 if there is no reason not to support lua 5.2 in the proctrack lua plugin.

Thanks,

Roland

**Comment by jette** [comment]
Thanks. This will be in the version 14.11.6 release. The commit is here:
https://github.com/SchedMD/slurm/commit/c78247f151bf870436fd189b55c10043e8c5805a

**Comment by rfehren** [comment]
Ok, thanks.
