### ISSUE TITLE
Array jobs are running only 1 job per node and not per core

### ISSUE THREAD

**Issue by mvala** [SchedMD/slurm#111]
I just updated slurm to 14.11.6 and when i run my test job i see that job is running only one job per 
node and not per core. Note:
```
NodeName=comp[01] CPUs=12 Sockets=2 CoresPerSocket=6 ThreadsPerCore=1 State=UNKNOWN
NodeName=comp[56] CPUs=16 Sockets=2 CoresPerSocket=8 ThreadsPerCore=1 State=UNKNOWN
```
And here example job
```
sbatch -p test -a 0-20 test.sh 
```
here is squeue output 
```
JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
26_[2-20]      test  test.sh    mvala PD       0:00      1 (Resources)
26_0      test  test.sh    mvala  R       0:05      1 comp01
26_1      test  test.sh    mvala  R       0:05      1 comp56
```

**Comment by accre** [comment]
See this thread: https://groups.google.com/forum/#!topic/slurm-devel/aSkJomPNXYA

You need to configure a DefMemPerCPU since in 14.11.6 SLURM allocates all memory on a node to a job not explicitly requesting memory.

**Comment by mvala** [comment]
Thanks it is working
