### ISSUE TITLE
squeue does not indicate whether min_memory is per node or per cpu

### ISSUE THREAD

**Issue by giovtorres** [SchedMD/slurm#115]
The squeue command does not indicate whether the MIN_MEMORY value for a given jobid is allocated per node or per cpu, while sacct and scontrol both do.  Is it possible to get this from squeue?  If not, would it be possible to have this ability added into squeue?

```
$ squeue -j <jobid> -o %m
MIN_MEMORY
1000
```

```
$ scontrol show job <jobid> | grep MinMem
   MinCPUsNode=1 MinMemoryCPU=2000M MinTmpDiskNode=0

$ scontrol show job <jobid> | grep MinMem
   MinCPUsNode=1 MinMemoryNode=1.50G MinTmpDiskNode=0
```

```
$ sacct --format=ReqMem -j <jobid>
    ReqMem 
---------- 
    1.50Gn
```

**Comment by giovtorres** [comment]
Ping.

Not sure if anyone saw this or knows if this could be added into a future release.  I can close the issue otherwise.

Thanks.

**Comment by jette** [comment]
someone will look at this when we have time...

**Comment by giovtorres** [comment]
Thanks!

**Comment by dannyauble** [comment]
You might be better off opening an enhancement request on bugs.schedmd.com with a patch (if possible) as it is how we keep track of these things instead of github.
